name: Salavat Khanov
description: iOS Developer with a Passion for Creativity
url: http://localhost:4000
blog_url: http://localhost:4000/blog
email: hello@khanov.me
twitter: https://twitter.com/khanov
version: 1.0
markdown: redcarpet
pygments: true
permalink: /posts/:title.html

gems:
  - jekyll-time-to-read
